#!/usr/bin/env Rscript
# RE-AIM site-level analytics and visualization
# Author: autogenerated by Codex agent

suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(scales)
  library(glue)
})

# ggprism styling; fallback to custom theme if package not installed
has_ggprism <- requireNamespace("ggprism", quietly = TRUE)
if (has_ggprism) library(ggprism)

# Prism-inspired theme helper -------------------------------------------------
theme_prism_safe <- function(base_size = 14, base_family = "Helvetica") {
  if (has_ggprism) {
    ggprism::theme_prism(base_size = base_size, base_family = base_family) +
      theme(
        # remove full panel border (top/right box)
        panel.border = element_blank(),

        # keep only left/bottom axis lines
        axis.line = element_line(color = "black", linewidth = 0.8),
        axis.line.x.top = element_blank(),
        axis.line.y.right = element_blank(),

        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(color = "black", linewidth = 0.4),
        plot.title = element_text(face = "bold"),
        plot.margin = margin(t = 8, r = 14, b = 22, l = 10)
      )
  } else {
    theme_bw(base_size = base_size, base_family = base_family) +
      theme(
        panel.border = element_blank(),
        axis.line = element_line(color = "black", linewidth = 0.8),
        axis.line.x.top = element_blank(),
        axis.line.y.right = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks = element_line(color = "black", linewidth = 0.4),
        plot.title = element_text(face = "bold"),
        plot.margin = margin(t = 8, r = 14, b = 22, l = 10)
      )
  }
}


scale_color_prism_safe <- function(palette = "floral") {
  if (has_ggprism) {
    ggprism::scale_color_prism(palette = palette)
  } else {
    scale_color_brewer(palette = "Dark2")
  }
}

scale_fill_prism_safe <- function(palette = "floral") {
  if (has_ggprism) {
    ggprism::scale_fill_prism(palette = palette)
  } else {
    scale_fill_brewer(palette = "Set2")
  }
}

theme_set(theme_prism_safe())

# Optional janitor clean_names; fallback if unavailable
has_janitor <- requireNamespace("janitor", quietly = TRUE)
if (has_janitor) {
  clean_names_safe <- janitor::clean_names
} else {
  clean_names_safe <- function(dat) {
    new <- names(dat) %>%
      str_replace_all("[^A-Za-z0-9]+", "_") %>%
      str_replace_all("_+", "_") %>%
      str_remove_all("^_|_$") %>%
      str_to_lower()
    names(dat) <- new
    dat
  }
}

# Paths -----------------------------------------------------------------------
data_path <- file.path("data", "reaim_site_level.csv")
fig_dir <- "figures"
tab_dir <- "tables"
dir.create(fig_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(tab_dir, showWarnings = FALSE, recursive = TRUE)

# Helpers ---------------------------------------------------------------------
wrap_cap <- function(text, width = 90) stringr::str_wrap(text, width)

add_caption_wrap <- function(plot_obj, width = 90) {
  if (!is.null(plot_obj$labels$caption)) {
    plot_obj <- plot_obj + labs(caption = wrap_cap(plot_obj$labels$caption, width))
  }
  plot_obj
}

save_plot <- function(plot, filename, width = 9, height = 6) {
  plot <- add_caption_wrap(plot)
  ggsave(file.path(fig_dir, filename), plot, width = width, height = height, dpi = 320)
}

clean_site_label <- function(x) {
  x %>%
    str_replace_all("\\.", " ") %>%
    str_replace_all("_", " ") %>%
    str_to_title()
}

wrap_site_label <- function(x) {
  x %>% str_replace("^South ", "South\n")
}

label_nudge_y <- 0.25 # global vertical nudge for point labels

# Data prep -------------------------------------------------------------------
raw <- readr::read_csv(data_path, col_types = cols(.default = col_character()))

long <- raw %>%
  clean_names_safe() %>%
  filter(!is.na(variables), variables != "") %>%
  pivot_longer(-variables, names_to = "site", values_to = "value") %>%
  mutate(site = clean_site_label(site))

wide <- long %>%
  pivot_wider(names_from = variables, values_from = value) %>%
  mutate(across(-c(site, operation_start), as.numeric),
         operation_start = lubridate::mdy(operation_start))

site_df <- wide %>%
  mutate(
    medicaid_pct = medicaid / pt_enrolled * 100,
    reach_per_month = pt_enrolled / pmax(operation_months, 1),
    reach_2020_2021_per_month = pt_enrolled / pmax(operation_months_2020_2021, 1),
    adherence_baseline_pct = adh_baseline / pt_enrolled * 100,
    adherence_y1_pct = adh_baseline_y1 / pt_enrolled * 100,
    adherence_y2_pct = adh_baseline_y2 / pt_enrolled * 100,
    adherence_any_pct = adh_baseline_any / pt_enrolled * 100,
    case_mgmt_mean = case_mgmt_any_mean,
    pharm_return_mean = pharm_return_any_mean,
    substance_any_pct = substance_any / pt_enrolled * 100,
    past_hosp_pct = past_hosp / pt_enrolled * 100,
    y2_y1_adherence_ratio = if_else(adh_baseline_y1 > 0, adh_baseline_y2 / adh_baseline_y1, NA_real_),
    pharm_y2_y1_ratio = if_else(pharm_return_y1 > 0, pharm_return_y2 / pharm_return_y1, NA_real_)
  ) %>%
  arrange(desc(pt_enrolled)) %>%
  mutate(site = factor(site, levels = site))

# Label table for plotting
site_labels <- tibble(
  site = levels(site_df$site),
  site_label = levels(site_df$site)
)

# Pattern discovery -----------------------------------------------------------
rank_metrics <- site_df %>%
  select(site, reach_abs_pct, adherence_any_pct, case_mgmt_mean,
         pharm_return_mean, medicaid_pct, comorbidity_charlson_mean,
         substance_any_pct) %>%
  pivot_longer(-site, names_to = "metric", values_to = "value") %>%
  group_by(metric) %>%
  mutate(rank_desc = min_rank(desc(value)),
         rank_asc = min_rank(value)) %>%
  ungroup()

rank_summary <- rank_metrics %>%
  group_by(metric) %>%
  summarise(
    top_site = site[which.min(rank_desc)],
    top_value = value[which.min(rank_desc)],
    bottom_site = site[which.min(rank_asc)],
    bottom_value = value[which.min(rank_asc)],
    .groups = "drop"
  )

readr::write_csv(rank_summary, file.path(tab_dir, "rank_summary.csv"))

# Contradiction detection -----------------------------------------------------
q <- function(var, p) quantile(site_df[[var]], probs = p, na.rm = TRUE)

contradictions <- list(
  high_medicaid_high_adherence = site_df %>%
    filter(medicaid_pct >= q("medicaid_pct", 0.75),
           adherence_any_pct >= q("adherence_any_pct", 0.75)) %>%
    mutate(reason = "High Medicaid share but strong adherence"),
  low_medicaid_low_adherence = site_df %>%
    filter(medicaid_pct <= q("medicaid_pct", 0.25),
           adherence_any_pct <= q("adherence_any_pct", 0.25)) %>%
    mutate(reason = "Low Medicaid and low adherence; potential equity gap"),
  low_reach_high_adherence = site_df %>%
    filter(reach_abs_pct <= q("reach_abs_pct", 0.25),
           adherence_any_pct >= q("adherence_any_pct", 0.75)) %>%
    mutate(reason = "Low reach but strong adherence among enrolled"),
  high_case_low_adherence = site_df %>%
    filter(case_mgmt_mean >= q("case_mgmt_mean", 0.75),
           adherence_any_pct <= q("adherence_any_pct", 0.25)) %>%
    mutate(reason = "High case management intensity but low adherence"),
  high_adherence_low_pharm = site_df %>%
    filter(adherence_any_pct >= q("adherence_any_pct", 0.75),
           pharm_return_mean <= q("pharm_return_mean", 0.25)) %>%
    mutate(reason = "High adherence with limited pharmacist returns"),
  substance_diverge = site_df %>%
    filter(substance_any_pct >= q("substance_any_pct", 0.75),
           adherence_any_pct <= q("adherence_any_pct", 0.5)) %>%
    mutate(reason = "Higher substance use burden with weaker adherence")
)

contradiction_tbl <- bind_rows(contradictions, .id = "pattern") %>%
  select(pattern, site, medicaid_pct, adherence_any_pct, case_mgmt_mean,
         pharm_return_mean, substance_any_pct, reason)

readr::write_csv(contradiction_tbl, file.path(tab_dir, "contradictions.csv"))

# Anomaly detection -----------------------------------------------------------
anomaly_flags <- list()

anomaly_flags$medicaid_zero <- site_df %>%
  filter(is.na(medicaid_pct) | medicaid_pct < 1) %>%
  transmute(site, issue = "Very low/zero Medicaid count")

anomaly_flags$sd_outlier <- site_df %>%
  mutate(sd_ratio_case = case_mgmt_any_stddev / pmax(case_mgmt_mean, 0.01),
         sd_ratio_pharm = pharm_return_any_stddev / pmax(pharm_return_mean, 0.01)) %>%
  filter(sd_ratio_case > 3 | sd_ratio_pharm > 3) %>%
  transmute(site, issue = "Very wide spread in case management or pharmacy returns")

anomaly_flags$missing_counts <- site_df %>%
  select(site, starts_with("comorbidity"), starts_with("substance"),
         medicaid, past_hosp) %>%
  pivot_longer(-site, names_to = "field", values_to = "value") %>%
  filter(is.na(value)) %>%
  transmute(site, issue = paste("Missing", field))

anomaly_tbl <- bind_rows(anomaly_flags, .id = "flag_type") %>%
  distinct()

readr::write_csv(anomaly_tbl, file.path(tab_dir, "anomalies.csv"))

# Clustering ------------------------------------------------------------------
cluster_vars <- site_df %>%
  select(site, reach_per_month, adherence_any_pct, medicaid_pct,
         case_mgmt_mean, pharm_return_mean)

scaled <- cluster_vars %>%
  column_to_rownames("site") %>%
  scale()

set.seed(123)
km <- kmeans(scaled, centers = 3, nstart = 25)

cluster_assign <- cluster_vars %>%
  mutate(cluster = km$cluster)

cluster_summary <- cluster_assign %>%
  group_by(cluster) %>%
  summarise(across(-site, ~mean(.x, na.rm = TRUE)), n_sites = n(), .groups = "drop")

overall_medians <- cluster_vars %>%
  summarise(across(-site, ~median(.x, na.rm = TRUE)))

cluster_labels <- cluster_summary %>%
  mutate(
    reach_flag = if_else(reach_per_month >= overall_medians$reach_per_month, "High Reach", "Lower Reach"),
    adh_flag = if_else(adherence_any_pct >= overall_medians$adherence_any_pct, "High Adherence", "Lower Adherence"),
    medicaid_flag = if_else(medicaid_pct >= overall_medians$medicaid_pct, "High Medicaid", "Lower Medicaid"),
    case_flag = if_else(case_mgmt_mean >= overall_medians$case_mgmt_mean, "High Case Mgmt", "Lean Case Mgmt"),
    pharm_flag = if_else(pharm_return_mean >= overall_medians$pharm_return_mean, "High Pharmacy", "Lean Pharmacy"),
    profile_label = paste(reach_flag, adh_flag, medicaid_flag, case_flag, pharm_flag, sep = " / ")
  ) %>%
  select(cluster, profile_label)

cluster_assign <- cluster_assign %>%
  left_join(cluster_labels, by = "cluster")

readr::write_csv(cluster_assign, file.path(tab_dir, "cluster_assignments.csv"))
readr::write_csv(cluster_summary, file.path(tab_dir, "cluster_summary.csv"))

# Narrative bullets -----------------------------------------------------------
pattern_notes <- rank_summary %>%
  mutate(note = glue::glue("{metric}: {top_site} highest ({round(top_value,1)}), {bottom_site} lowest ({round(bottom_value,1)}).")) %>%
  pull(note)

writeLines(pattern_notes, file.path(tab_dir, "pattern_notes.txt"))

# Plot data prep --------------------------------------------------------------
adherence_long <- site_df %>%
  select(site, adherence_baseline_pct, adherence_y1_pct, adherence_y2_pct) %>%
  pivot_longer(-site, names_to = "period", values_to = "adherence") %>%
  mutate(period = factor(period, levels = c("adherence_baseline_pct", "adherence_y1_pct", "adherence_y2_pct"),
                         labels = c("Baseline", "Year 1", "Year 2")))

reach_long <- site_df %>%
  select(site, reach_abs_pct, reach_per_month, reach_2020_2021_per_month) %>%
  pivot_longer(-site, names_to = "metric", values_to = "value") %>%
  mutate(metric = factor(metric,
                         levels = c("reach_abs_pct", "reach_per_month", "reach_2020_2021_per_month"),
                         labels = c("Reach %", "Reach per month", "Reach per month (2020-21)")))

cm_bins <- site_df %>%
  select(site, case_mgmt_none, case_mgmt_1_2, case_mgmt_3_6, case_mgmt_7_10, case_mgmt_10_plus) %>%
  pivot_longer(-site, names_to = "band", values_to = "count") %>%
  mutate(band = factor(band, levels = c("case_mgmt_none", "case_mgmt_1_2", "case_mgmt_3_6", "case_mgmt_7_10", "case_mgmt_10_plus"),
                       labels = c("None", "1-2", "3-6", "7-10", "10+")),
         pct = count / site_df$pt_enrolled[match(site, site_df$site)] * 100)

substance_long <- site_df %>%
  select(site, substance_alcohol, substance_drug, substance_any) %>%
  pivot_longer(-site, names_to = "type", values_to = "count") %>%
  mutate(type = factor(type, levels = c("substance_alcohol", "substance_drug", "substance_any"),
                       labels = c("Alcohol use dx", "Drug use dx", "Any SUD dx")),
         pct = count / site_df$pt_enrolled[match(site, site_df$site)] * 100)

comorbidity_long <- site_df %>%
  select(site, comorbidity_none, comorbidity_1_2, comorbidity_2_plus) %>%
  pivot_longer(-site, names_to = "cat", values_to = "count") %>%
  mutate(cat = factor(cat, levels = c("comorbidity_none", "comorbidity_1_2", "comorbidity_2_plus"),
                      labels = c("0", "1-2", "3+")),
         pct = count / site_df$pt_enrolled[match(site, site_df$site)] * 100)

cor_vars <- site_df %>%
  select(adherence_baseline_pct, adherence_y1_pct, adherence_y2_pct,
         adherence_any_pct, reach_abs_pct, reach_per_month, medicaid_pct,
         case_mgmt_mean, pharm_return_mean, substance_any_pct, comorbidity_charlson_mean)

cor_long <- cor(cor_vars, use = "pairwise.complete.obs") %>%
  as.data.frame() %>%
  rownames_to_column("var_x") %>%
  pivot_longer(-var_x, names_to = "var_y", values_to = "correlation")

# Plots -----------------------------------------------------------------------
p_reach_pct <- site_df %>%
  ggplot(aes(site, reach_abs_pct, fill = site)) +
  geom_col(color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Reach percent by site",
       y = "Reach (%) of target population", x = NULL,
       caption = "Higher bars indicate stronger initial reach into the target population.") +
  theme(legend.position = "none")
save_plot(p_reach_pct, "reach_pct_by_site.png", width = 8, height = 6)

p_reach_month <- reach_long %>%
  filter(metric != "Reach %") %>%
  ggplot(aes(site, value, fill = metric)) +
  geom_col(position = position_dodge(width = 0.7), color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Reach velocity",
       y = "Patients enrolled per month", x = NULL,
       fill = "Metric",
       caption = "Contrasts total reach rate vs. 2020–21 period to show COVID-era performance.") +
  theme(legend.position = "bottom")
save_plot(p_reach_month, "reach_per_month.png", width = 9, height = 6)

p_reach_dual <- reach_long %>%
  filter(metric != "Reach per month") %>%
  ggplot(aes(metric, value, fill = metric)) +
  geom_boxplot(alpha = 0.4, width = 0.3, outlier.shape = NA) +
  geom_jitter(aes(color = site), width = 0.15, height = 0, size = 2.8, alpha = 0.8) +
  scale_fill_prism_safe() +
  scale_color_prism_safe() +
  labs(title = "Reach comparison overall vs. 2020–21",
       y = "Reach (%)", x = NULL,
       caption = "Dots are sites; shows whether pandemic-era reach diverged from overall performance.") +
  theme(legend.position = "bottom")
save_plot(p_reach_dual, "reach_comparison.png", width = 8, height = 6)

# Reach timeline: program age vs velocity
p_reach_timeline <- site_df %>%
  mutate(site_label_wrap = wrap_site_label(site)) %>%
  ggplot(aes(operation_months, reach_per_month, label = site_label_wrap, color = site_label_wrap, size = reach_abs_pct)) +
  geom_point(alpha = 0.85) +
  geom_text(nudge_y = label_nudge_y, size = 3, show.legend = FALSE, vjust = 0) +
  scale_color_prism_safe() +
  scale_size_continuous(range = c(3, 9)) +
  labs(
    title = "Program age vs reach velocity",
    x = "Months in operation",
    y = "Reach per month",
    size = "Reach (%) of target",
    caption = "Younger programs (e.g., Santa Rosa, South Sacramento) have low cumulative reach but competitive monthly velocity. Bubble size = overall reach %."
  ) +
  theme(legend.position = "right",
        plot.margin = margin(10, 20, 20, 10)) +
  coord_cartesian(clip = "off")
save_plot(p_reach_timeline, "reach_age_vs_velocity.png", width = 9.5, height = 6.5)

p_adh_bar <- adherence_long %>%
  ggplot(aes(period, adherence, fill = period)) +
  geom_col(color = "black", width = 0.7, position = position_dodge2(preserve = "single")) +
  facet_wrap(~ site, ncol = 3) +
  scale_fill_prism_safe() +
  labs(title = "Adherence levels by period",
       y = "Adherence (% of enrolled)", x = NULL,
       caption = "Baseline reflects initial med adherence; Year 1/2 show maintenance over time.") +
  theme(legend.position = "bottom")
save_plot(p_adh_bar, "adherence_bar.png", width = 11, height = 9)

p_adh_line <- adherence_long %>%
  ggplot(aes(period, adherence, group = site, color = site)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2.5) +
  scale_color_prism_safe() +
  labs(title = "Adherence trajectories",
       y = "Adherence (%)", x = NULL,
       caption = "Lines show change from baseline through Year 2; flat or rising lines indicate durable adherence.") +
  theme(legend.position = "right")
save_plot(p_adh_line, "adherence_trajectories.png", width = 10, height = 6)

p_scatter_predictors <- site_df %>%
  select(site, adherence_any_pct, case_mgmt_mean, pharm_return_mean, medicaid_pct) %>%
  pivot_longer(-c(site, adherence_any_pct), names_to = "predictor", values_to = "value") %>%
  mutate(predictor = factor(predictor,
                            levels = c("case_mgmt_mean", "pharm_return_mean", "medicaid_pct"),
                            labels = c("Case mgmt mean", "Pharmacy return mean", "Medicaid %"))) %>%
  ggplot(aes(value, adherence_any_pct, color = site)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed") +
  scale_color_prism_safe() +
  facet_wrap(~ predictor, scales = "free_x") +
  labs(title = "Predictors of adherence", x = "Predictor value", y = "Adherence (%)",
       caption = "Dashed line shows overall trend; deviations highlight sites above/below expected adherence.") +
  theme(legend.position = "bottom")
save_plot(p_scatter_predictors, "adherence_predictors.png", width = 11, height = 7)

p_cor <- cor_long %>%
  ggplot(aes(var_x, var_y, fill = correlation)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#2166AC", mid = "white", high = "#B2182B", limits = c(-1, 1)) +
  coord_equal() +
  labs(title = "Correlation heatmap", x = NULL, y = NULL,
       caption = "Shows pairwise correlations among adherence and potential drivers.") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
save_plot(p_cor, "correlation_heatmap.png", width = 9, height = 8)

p_case_intensity <- site_df %>%
  ggplot(aes(site, case_mgmt_mean, fill = site)) +
  geom_col(color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Case management intensity", x = NULL, y = "Mean contacts",
       caption = "Higher bars signal more intensive care management per patient.") +
  theme(legend.position = "none")
save_plot(p_case_intensity, "case_management_intensity.png", width = 8, height = 6)

# Case management descriptive plot with IQR and median
case_mgmt_summary <- site_df %>%
  transmute(
    site,
    mean = case_mgmt_any_mean,
    sd = case_mgmt_any_stddev,
    median = case_mgmt_any_median,
    q1 = case_mgmt_any_median_q1,
    q3 = case_mgmt_any_median_q3
  )

readr::write_csv(case_mgmt_summary, file.path(tab_dir, "case_management_summary.csv"))

p_case_iqr <- case_mgmt_summary %>%
  ggplot(aes(site, mean, fill = site)) +
  geom_col(color = "black", width = 0.65, alpha = 0.75) +
  geom_errorbar(aes(ymin = q1, ymax = q3), width = 0.2, linewidth = 0.7) +
  geom_point(aes(y = median), shape = 21, size = 3, fill = "white", color = "black") +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Case management intensity with spread",
       x = NULL,
       y = "Contacts (mean with IQR, median point)",
       caption = "Bars show mean contacts; error bars show IQR; white dot marks median. Wide IQR suggests uneven workload distribution.") +
  theme(legend.position = "none")
save_plot(p_case_iqr, "case_management_intensity_iqr.png", width = 9, height = 6.5)

p_case_distribution <- cm_bins %>%
  ggplot(aes(band, pct, fill = band)) +
  geom_boxplot(width = 0.4, alpha = 0.7, outlier.shape = NA) +
  geom_jitter(aes(color = site), width = 0.15, height = 0, size = 2, alpha = 0.8) +
  scale_fill_prism_safe() +
  scale_color_prism_safe() +
  labs(title = "Case management distribution", x = "Contacts category", y = "Percent of enrolled",
       caption = "Shows proportion of patients in each case-management band by site.") +
  theme(legend.position = "bottom")
save_plot(p_case_distribution, "case_management_distribution.png", width = 9, height = 6)

p_pharm_returns <- site_df %>%
  ggplot(aes(site, pharm_return_mean, fill = site)) +
  geom_col(color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Pharmacist return visits", x = NULL, y = "Mean follow-ups",
       caption = "Higher values indicate more pharmacist engagement beyond intake.") +
  theme(legend.position = "none")
save_plot(p_pharm_returns, "pharmacist_returns.png", width = 8, height = 6)

p_comorbidity <- comorbidity_long %>%
  ggplot(aes(site, pct, fill = cat)) +
  geom_col(position = "fill", color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  scale_y_continuous(labels = percent) +
  labs(title = "Comorbidity mix", x = NULL, y = "Share of enrolled",
       fill = "Charlson score",
       caption = "Stacked bars show complexity of enrolled patients.") +
  theme(legend.position = "right")
save_plot(p_comorbidity, "comorbidity_mix.png", width = 9, height = 6)

p_substance <- substance_long %>%
  ggplot(aes(site, pct, fill = type)) +
  geom_col(position = "dodge", color = "black", width = 0.75) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Substance use diagnoses", x = NULL, y = "Percent of enrolled",
       caption = "Highlights SUD burden relative to caseload size.") +
  theme(legend.position = "bottom")
save_plot(p_substance, "substance_use.png", width = 10, height = 7)

# Medicaid exploration --------------------------------------------------------
medicaid_summary <- site_df %>%
  summarise(
    min = min(medicaid_pct, na.rm = TRUE),
    q1 = quantile(medicaid_pct, 0.25, na.rm = TRUE),
    median = median(medicaid_pct, na.rm = TRUE),
    q3 = quantile(medicaid_pct, 0.75, na.rm = TRUE),
    max = max(medicaid_pct, na.rm = TRUE),
    mean = mean(medicaid_pct, na.rm = TRUE),
    sd = sd(medicaid_pct, na.rm = TRUE)
  )
readr::write_csv(medicaid_summary, file.path(tab_dir, "medicaid_summary.csv"))

p_medicaid_bar <- site_df %>%
  mutate(site_med = if_else(site == "Fresno", "Fresno*", as.character(site)),
         site_med = factor(site_med, levels = if_else(site == "Fresno", "Fresno*", as.character(site)))) %>%
  ggplot(aes(site, medicaid_pct, fill = site)) +
  geom_col(aes(x = site_med), color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(
    title = "Medicaid mix by site",
    x = NULL,
    y = "Medicaid (% of enrolled)",
    caption = "Contrasts Medicaid proportion to flag equity and payer-mix differences. Fresno* has unusually low Medicaid; confirm data entry."
  ) +
  theme(legend.position = "none")
save_plot(p_medicaid_bar, "medicaid_by_site.png", width = 8, height = 6)

p_medicaid_scatter <- site_df %>%
  select(site, medicaid_pct, reach_abs_pct, adherence_any_pct) %>%
  mutate(site_med = if_else(site == "Fresno", "Fresno*", as.character(site))) %>%
  pivot_longer(c(reach_abs_pct, adherence_any_pct), names_to = "outcome", values_to = "value") %>%
  mutate(outcome = recode(outcome,
    reach_abs_pct = "Reach (%)",
    adherence_any_pct = "Adherence (%)"
  )) %>%
  ggplot(aes(medicaid_pct, value, color = site_med)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed", linewidth = 0.7) +
  facet_wrap(~outcome, scales = "free_y") +
  scale_color_prism_safe() +
  labs(
    title = "Medicaid mix vs reach and adherence",
    x = "Medicaid (% of enrolled)",
    y = NULL,
    caption = "Dashed line shows overall trend; points show whether high-Medicaid sites sustain reach/adherence. Fresno* has unusually low Medicaid; confirm data entry."
  ) +
  theme(legend.position = "bottom")
save_plot(p_medicaid_scatter, "medicaid_vs_outcomes.png", width = 10, height = 6.5)

# Substance use vs case management correlation plot
substance_case_cor <- cor(site_df$substance_any_pct, site_df$case_mgmt_mean, use = "complete.obs")

p_substance_case <- site_df %>%
  mutate(site_label_wrap = wrap_site_label(site)) %>%
  ggplot(aes(substance_any_pct, case_mgmt_mean)) +
  geom_point(aes(color = site_label_wrap), size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "black", linetype = "dashed", linewidth = 0.7) +
  geom_text(aes(label = site_label_wrap, color = site_label_wrap), nudge_y = label_nudge_y, size = 3, show.legend = FALSE, vjust = 0) +
  scale_color_prism_safe() +
  labs(title = "Case management intensity vs. substance use burden",
       x = "Substance use dx (% of enrolled)",
       y = "Case management mean contacts",
       caption = glue("Dashed line = overall linear trend (r = {round(substance_case_cor, 2)}). Points labeled by site highlight who is above/below expected CM given SUD burden.")) +
  theme(legend.position = "none",
        plot.margin = margin(10, 20, 20, 10)) +
  coord_cartesian(clip = "off")
save_plot(p_substance_case, "substance_case_management.png", width = 9, height = 6.5)

# Cluster visualization (reach vs adherence colored by cluster; size = Medicaid)
p_cluster <- cluster_assign %>%
  mutate(label_med = if_else(site == "Fresno", "Fresno*", as.character(site))) %>%
  mutate(label_wrap = wrap_site_label(label_med)) %>%
  ggplot(aes(reach_per_month, adherence_any_pct, color = factor(cluster), size = medicaid_pct, label = label_wrap)) +
  geom_point(alpha = 0.8) +
  geom_text(nudge_y = label_nudge_y, size = 3, show.legend = FALSE, vjust = 0) +
  scale_color_prism_safe(palette = "waves") +
  scale_size_continuous(range = c(3, 9)) +
  labs(
    title = "Site profiles: reach vs adherence by cluster",
    x = "Reach per month",
    y = "Adherence (%)",
    color = "Cluster",
    size = "Medicaid %",
    caption = "Clusters from k-means (3 centers). Larger points indicate higher Medicaid share. Fresno* has unusually low Medicaid; confirm data entry."
  ) +
  theme(legend.position = "right",
        plot.margin = margin(10, 20, 20, 10)) +
  coord_cartesian(clip = "off")
save_plot(p_cluster, "cluster_scatter.png", width = 10, height = 7)

p_maintenance <- site_df %>%
  ggplot(aes(site, y2_y1_adherence_ratio, fill = site)) +
  geom_col(color = "black", width = 0.7) +
  coord_flip() +
  scale_fill_prism_safe() +
  labs(title = "Maintenance: Year 2 vs Year 1 adherence", x = NULL, y = "Y2 / Y1 ratio",
       caption = "Values near 1 show stable adherence; below 1 signal drop-off.") +
  theme(legend.position = "none")
save_plot(p_maintenance, "adherence_maintenance_ratio.png", width = 8, height = 6)

p_pharm_stability <- site_df %>%
  mutate(site_label_wrap = wrap_site_label(site)) %>%
  ggplot(aes(pharm_return_y1, pharm_return_y2, label = site_label_wrap, color = site_label_wrap)) +
  geom_point(size = 3) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", linewidth = 0.6) +
  scale_color_prism_safe() +
  labs(title = "Pharmacist follow-up stability", x = "Year 1 returns", y = "Year 2 returns",
       caption = "Points below diagonal lost pharmacist engagement in Year 2.") +
  theme(legend.position = "none",
        plot.margin = margin(10, 20, 20, 10)) +
  coord_cartesian(clip = "off")
save_plot(p_pharm_stability, "pharmacist_stability.png", width = 7.5, height = 6.5)

p_stability_rank <- site_df %>%
  mutate(site_label_wrap = wrap_site_label(site)) %>%
  ggplot(aes(y2_y1_adherence_ratio, pharm_y2_y1_ratio, label = site_label_wrap, color = site_label_wrap)) +
  geom_point(size = 3) +
  geom_vline(xintercept = 1, linetype = "dashed", linewidth = 0.5) +
  geom_hline(yintercept = 1, linetype = "dashed", linewidth = 0.5) +
  scale_color_prism_safe() +
  labs(title = "Maintenance stability matrix",
       x = "Adherence Y2 / Y1", y = "Pharmacist returns Y2 / Y1",
       caption = "Upper-right quadrant indicates sites maintaining both adherence and pharmacist follow-up.") +
  theme(legend.position = "none",
        plot.margin = margin(10, 20, 20, 10)) +
  coord_cartesian(clip = "off")
save_plot(p_stability_rank, "stability_matrix.png", width = 8, height = 7)

# Tables for reporting --------------------------------------------------------
readr::write_csv(site_df, file.path(tab_dir, "site_metrics_derived.csv"))
readr::write_csv(adherence_long, file.path(tab_dir, "adherence_long.csv"))
readr::write_csv(reach_long, file.path(tab_dir, "reach_long.csv"))
readr::write_csv(cor_long, file.path(tab_dir, "correlations.csv"))

# Console output for quick reference -----------------------------------------
message("\nRank summary:\n")
print(rank_summary)

message("\nContradictions of interest:\n")
print(contradiction_tbl)

message("\nAnomaly flags:\n")
print(anomaly_tbl)

message("\nCluster profiles:\n")
print(cluster_summary %>% left_join(cluster_labels, by = "cluster"))

message("\nOutputs saved to 'figures/' and 'tables/'.\n")
# Optional ggprism styling; fallback to custom theme if package not installed
has_ggprism <- requireNamespace("ggprism", quietly = TRUE)
if (has_ggprism) {
  library(ggprism)
}

# Optional janitor clean_names; fallback if unavailable
has_janitor <- requireNamespace("janitor", quietly = TRUE)
if (has_janitor) {
  clean_names_safe <- janitor::clean_names
} else {
  clean_names_safe <- function(dat) {
    new <- names(dat) %>%
      str_replace_all("[^A-Za-z0-9]+", "_") %>%
      str_replace_all("_+", "_") %>%
      str_remove_all("^_|_$") %>%
      str_to_lower()
    names(dat) <- new
    dat
  }
}
